### ISSUE TITLE
How to change size of input box?

### ISSUE THREAD

**Issue by IStoleThePies** [yairEO/fancyInput#46]
How do I change the width and height of the input box in CSS?

**Comment by yairEO** [comment]
you must learn CSS first, I cannot be bothered with such basic questions because i'm a dick that has no time for such things

**Comment by IStoleThePies** [comment]
I know CSS. Are you kidding me?

**Comment by yairEO** [comment]
I am not maintaining this script at all..I don't even remember how the code goes..been years..I really don't have time for it sorry, I have new cooler scripts to write!
