### ISSUE TITLE
CTRL + A, Backspace/Delete = Broken

### ISSUE THREAD

**Issue by Stoyvo** [yairEO/fancyInput#51]
If you CTRL + A and press Delete quickly, you're presented with a broken input. Control error is:

fancyInput.js:165 Uncaught TypeError: Cannot read property 'offsetLeft' of undefined(…)

Windows 10 + Chrome 54

**Comment by dyanakiev** [comment]
I can confirm this is not fixed..

**Comment by yairEO** [comment]
just tested on latest Chrome no my wonderful windows 7 and it works. I can't see any reason why it wouldn't

**Comment by yairEO** [comment]
please try now
